"""Unsupervised lookup tables computed on the split being processed.

Nothing here reads labels, so the same code runs on train and on test (and
on countries never seen in training, e.g. France):

* token IDF for name and address tokens (per country)
* how many Source 1 / Source 2+3 records share an exact core name (ambiguity)
* token counts in Source 1 names (a word never seen in any Source 1 name is
  likely a made-up trade name or a typo)
* "modifier" statistics: when a candidate name equals the Source 1 name plus
  one extra word w (or minus one word), how often does the house number still
  agree? Look-alike businesses are generated by adding a word such as
  "Holdings" and moving the house number, while benign noise words such as
  "Services" keep the address, so this rate separates the two kinds of words
  without any labels (corr. 0.88 with label precision on train).
"""
import math

import polars as pl

from . import features as F
from .config import work

SMOOTH = 20.0


def idf_tables(R: pl.DataFrame) -> dict:
    out = {}
    for col, name in (("n_core", "name"), ("a_full", "addr")):
        tok = (R.select("country", pl.col(col).str.split(" ").list.unique().alias("w"))
               .explode("w").filter(pl.col("w") != ""))
        n = R.group_by("country").agg(pl.len().alias("n"))
        df = tok.group_by("country", "w").agg(pl.len().alias("df")).join(n, on="country")
        out[name] = df.select("country", "w", (pl.col("n").cast(pl.Float64) / pl.col("df")).log()
                              .cast(pl.Float32).alias("idf"))
    return out


def name_counts(R: pl.DataFrame) -> pl.DataFrame:
    """Number of S1 and of S2/S3 records per (country, exact core name)."""
    return (R.group_by("country", "n_core")
            .agg((pl.col("src") == 1).sum().cast(pl.Float32).alias("cnt_s1"),
                 (pl.col("src") != 1).sum().cast(pl.Float32).alias("cnt_t")))


def s1_vocab(R: pl.DataFrame) -> pl.DataFrame:
    return (R.filter(pl.col("src") == 1)
            .select("country", pl.col("n_full").str.split(" ").list.unique().alias("w"))
            .explode("w").group_by("country", "w").agg(pl.len().cast(pl.Float32).alias("s1cnt")))


def modifier_stats(split: str, R: pl.DataFrame) -> pl.DataFrame:
    """Per (country, kind, word): house-number agreement rate among blocked pairs."""
    S = pl.read_parquet(work(f"{split}_stage_a_scores.parquet"), columns=["qr", "tr"])
    cols = R.select("country", "n_core", "a_hnum")
    parts = []
    step = 10_000_000
    for s in range(0, S.height, step):
        c = S.slice(s, step)
        q = cols[c["qr"].to_numpy()]
        t = cols[c["tr"].to_numpy()]
        d = pl.DataFrame({
            "country": q["country"],
            "nt1": q["n_core"].str.split(" "), "nt2": t["n_core"].str.split(" "),
            "h1": q["a_hnum"], "h2": t["a_hnum"],
        }).filter((pl.col("h1") != "") & (pl.col("h2") != ""))
        d = d.with_columns(extra=pl.col("nt2").list.set_difference(pl.col("nt1")),
                           missing=pl.col("nt1").list.set_difference(pl.col("nt2")),
                           heq=(pl.col("h1") == pl.col("h2")).cast(pl.Float32))
        ne, nm = pl.col("extra").list.len(), pl.col("missing").list.len()
        parts += [
            d.filter((ne == 1) & (nm == 0)).select("country", pl.lit("add").alias("kind"),
                                                   pl.col("extra").list.first().alias("w"), "heq"),
            d.filter((ne == 0) & (nm == 1)).select("country", pl.lit("del").alias("kind"),
                                                   pl.col("missing").list.first().alias("w"), "heq"),
            d.filter((ne == 1) & (nm == 1)).select("country", pl.lit("rep").alias("kind"),
                                                   pl.col("extra").list.first().alias("w"), "heq"),
        ]
    d = pl.concat(parts)
    base = d.group_by("country", "kind").agg(pl.col("heq").mean().alias("base"))
    st = (d.group_by("country", "kind", "w").agg(pl.len().alias("n"), pl.col("heq").sum().alias("s"))
          .join(base, on=["country", "kind"])
          .with_columns(rate=((pl.col("s") + SMOOTH * pl.col("base")) / (pl.col("n") + SMOOTH)).cast(pl.Float32))
          .with_columns(rel=(pl.col("rate") / pl.col("base").clip(1e-3)).cast(pl.Float32),
                        logn=(pl.col("n").cast(pl.Float32) + 1).log()))
    return st.select("country", "kind", "w", "rate", "rel", "logn")


def build(split: str):
    R = F.load_records(split)
    idf = idf_tables(R)
    idf["name"].write_parquet(work("stats", split, "idf_name.parquet"))
    idf["addr"].write_parquet(work("stats", split, "idf_addr.parquet"))
    name_counts(R).write_parquet(work("stats", split, "name_counts.parquet"))
    s1_vocab(R).write_parquet(work("stats", split, "s1_vocab.parquet"))
    modifier_stats(split, R).write_parquet(work("stats", split, "modifiers.parquet"))


def load(split: str) -> dict:
    names = ["idf_name", "idf_addr", "name_counts", "s1_vocab", "modifiers"]
    return {n: pl.read_parquet(work("stats", split, f"{n}.parquet")) for n in names}


if __name__ == "__main__":
    import sys
    for sp in sys.argv[1:] or ["train"]:
        build(sp)
